server:
  port: 8080
spring:
  application:
    name: customer
  datasource:
    username: admin
    url: jdbc:postgresql://localhost:5432/textme
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false
